###
POST http://localhost:5000/users/create-user
Content-Type: application/json

{
    "firstname": "Donald",
    "middlename": "G",
    "lastname": "Henderson",
    "mobilenumber": "970-301-9004",
    "alternate_mobilenumber": "970-336-3842",
    "address" : "146 Timberbrook Lane, Greeley, Colorado(CO), 80631",
    "username": "Shane Watson",
    "password": "alex43"
}

###
GET http://localhost:5000/users

###
PUT http://localhost:5000/users/update-user/Donald-Henderson
Content-Type: application/json

{
    "firstname": "Donald",
    "middlename": "G",
    "lastname": "Trump",
    "mobilenumber": "970-301-2022",
    "alternate_mobilenumber": "970-336-2020",
    "address" : "146 Timberbrook Lane, Greeley, Colorado(CO), 80631",
    "username": "donaldgt",
    "password": "donald43gt"
}

###
DELETE http://localhost:5000/users/delete-user/Donald-Henderson